const ACTION_ENUM = Object.freeze({
    MOVIE_LIST_REQUEST_STATUS_CHANGED: 'MOVIE_LIST_REQUEST_STATUS_CHANGED',
    MOVIE_DETAIL_REQUEST_STATUS_CHANGED: 'MOVIE_DETAIL_REQUEST_STATUS_CHANGED',
    MOVIE_LIST_DATA_LIST_CHANGED: 'MOVIE_LIST_DATA_LIST_CHANGED',
    MOVIE_LIST_SELECTED_DATA_CHANGED: 'MOVIE_LIST_SELECTED_DATA_CHANGED',
    MOVIE_LIST_MAX_PAGE_CHANGED: 'MOVIE_LIST_MAX_PAGE_CHANGED',
    MOVIE_LIST_SEARCH_DATA_CHANGED: 'MOVIE_LIST_SEARCH_DATA_CHANGED'
});

export default ACTION_ENUM;